interface Env {
  CRABBOX_TOKEN: string;
  BOOTSTRAP_SIGNING_SECRET: string;
  SESSION_SIGNING_SECRET: string;
  INVOCATION_SIGNING_SECRET: string;
  RUNTIME_SIGNING_SECRET: string;
  VAULT_MASTER_KEY: string;
  OPENAI_API_KEY?: string;
  CRABHELM_SLACK?: "on" | "off";
  SLACK_BOT_TOKEN?: string;
  SLACK_APP_TOKEN?: string;
  SLACK_SIGNING_SECRET?: string;
  GITHUB_OAUTH_CLIENT_ID: string;
  GITHUB_OAUTH_CLIENT_SECRET: string;
  CF_ACCESS_TEAM_DOMAIN: string;
  CF_ACCESS_AUD: string;
  CF_ACCESS_ADMIN_EMAILS: string;
  CF_ACCESS_ADMIN_GROUPS?: string;
  CRABHELM_PROBE_EMAIL: string;
  RUNTIME_URL: string;
  CRABHELM_CLAWROUTER?: "on" | "off";
  CLAWROUTER_BASE_URL?: string;
  CLAWROUTER_TENANT_ID?: string;
  CLAWROUTER_ALLOWED_PROVIDERS?: string;
  CLAWROUTER_MODEL_PROVIDER_MAP?: string;
  CLAWROUTER_DEFAULT_MODEL?: string;
  CLAWROUTER_ADMIN_TOKEN?: string;
  CLAWROUTER_CREDENTIAL_SECRET?: string;
  CLAWROUTER_ACCESS_CLIENT_ID?: string;
  CLAWROUTER_ACCESS_CLIENT_SECRET?: string;
  CRABHELM_PROMETHEUS?: "on" | "off";
  METRICS_BEARER_TOKEN?: string;
}

declare namespace Cloudflare {
  interface Env {
    CRABBOX_TOKEN: string;
    BOOTSTRAP_SIGNING_SECRET: string;
    SESSION_SIGNING_SECRET: string;
    INVOCATION_SIGNING_SECRET: string;
    RUNTIME_SIGNING_SECRET: string;
    VAULT_MASTER_KEY: string;
    OPENAI_API_KEY?: string;
    CRABHELM_SLACK?: "on" | "off";
    SLACK_BOT_TOKEN?: string;
    SLACK_APP_TOKEN?: string;
    SLACK_SIGNING_SECRET?: string;
    CF_ACCESS_TEAM_DOMAIN: string;
    CF_ACCESS_AUD: string;
    CF_ACCESS_ADMIN_EMAILS: string;
    CF_ACCESS_ADMIN_GROUPS?: string;
    CRABHELM_PROBE_EMAIL: string;
    CRABHELM_CLAWROUTER?: "on" | "off";
    CLAWROUTER_BASE_URL?: string;
    CLAWROUTER_TENANT_ID?: string;
    CLAWROUTER_ALLOWED_PROVIDERS?: string;
    CLAWROUTER_MODEL_PROVIDER_MAP?: string;
    CLAWROUTER_DEFAULT_MODEL?: string;
    CRABHELM_PROMETHEUS?: "on" | "off";
  }
}
